enabled: true
description: Telegram polling server for receiving and sending messages with session management and pipeline integration
dependencies:
  - python-telegram-bot
  - python-dotenv
  - psutil
